
// change the dirname to where you keep your Sequelize files
var orm_dir = __dirname + '/orm/';

//init yaml
require('js-yaml');

config = require(__dirname + '/config.yaml');


//initialize Seq
Sequelize = require('sequelize');
sequelize = new Sequelize(config.database,config.user,config.password);

app.get('/', ensureAuthenticated, function(req, res){
        //Create a new object here...
        res.render('list'); //which loads the index
});


//Begin autogenerated Objects...

//importing Addresss from table cred:Addresss
var Addresss = sequelize.import(orm_dir + 'Addresss.orm.js');
// State_id looks like an association
// County_id looks like an association


app.post('/API/Addresss/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Addresss saved <a href='/'>home</a>');
});

app.get('/API/Addresss/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Addresss.rawAttributes);

	__.each(Addresss.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Addresss',to_template); //which loads views/Addresss.dust
});

app.get('/API/Addresss/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Addresss'); //which loads views/Addresss.dust
});


//importing Boards from table cred:Boards
var Boards = sequelize.import(orm_dir + 'Boards.orm.js');
// Address_id looks like an association
// Phone_id looks like an association
// Fax_Phone_id looks like an association


app.post('/API/Boards/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Boards saved <a href='/'>home</a>');
});

app.get('/API/Boards/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Boards.rawAttributes);

	__.each(Boards.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Boards',to_template); //which loads views/Boards.dust
});

app.get('/API/Boards/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Boards'); //which loads views/Boards.dust
});


//importing Carriers from table cred:Carriers
var Carriers = sequelize.import(orm_dir + 'Carriers.orm.js');


app.post('/API/Carriers/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Carriers saved <a href='/'>home</a>');
});

app.get('/API/Carriers/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Carriers.rawAttributes);

	__.each(Carriers.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Carriers',to_template); //which loads views/Carriers.dust
});

app.get('/API/Carriers/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Carriers'); //which loads views/Carriers.dust
});


//importing Countys from table cred:Countys
var Countys = sequelize.import(orm_dir + 'Countys.orm.js');


app.post('/API/Countys/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Countys saved <a href='/'>home</a>');
});

app.get('/API/Countys/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Countys.rawAttributes);

	__.each(Countys.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Countys',to_template); //which loads views/Countys.dust
});

app.get('/API/Countys/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Countys'); //which loads views/Countys.dust
});


//importing CredentialOrganizations from table cred:CredentialOrganizations
var CredentialOrganizations = sequelize.import(orm_dir + 'CredentialOrganizations.orm.js');


app.post('/API/CredentialOrganizations/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('CredentialOrganizations saved <a href='/'>home</a>');
});

app.get('/API/CredentialOrganizations/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(CredentialOrganizations.rawAttributes);

	__.each(CredentialOrganizations.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('CredentialOrganizations',to_template); //which loads views/CredentialOrganizations.dust
});

app.get('/API/CredentialOrganizations/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('CredentialOrganizations'); //which loads views/CredentialOrganizations.dust
});


//importing EducationInstitutions from table cred:EducationInstitutions
var EducationInstitutions = sequelize.import(orm_dir + 'EducationInstitutions.orm.js');
// Address_id looks like an association
// Phone_id looks like an association


app.post('/API/EducationInstitutions/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('EducationInstitutions saved <a href='/'>home</a>');
});

app.get('/API/EducationInstitutions/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(EducationInstitutions.rawAttributes);

	__.each(EducationInstitutions.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('EducationInstitutions',to_template); //which loads views/EducationInstitutions.dust
});

app.get('/API/EducationInstitutions/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('EducationInstitutions'); //which loads views/EducationInstitutions.dust
});


//importing EducationLevels from table cred:EducationLevels
var EducationLevels = sequelize.import(orm_dir + 'EducationLevels.orm.js');


app.post('/API/EducationLevels/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('EducationLevels saved <a href='/'>home</a>');
});

app.get('/API/EducationLevels/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(EducationLevels.rawAttributes);

	__.each(EducationLevels.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('EducationLevels',to_template); //which loads views/EducationLevels.dust
});

app.get('/API/EducationLevels/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('EducationLevels'); //which loads views/EducationLevels.dust
});


//importing Genders from table cred:Genders
var Genders = sequelize.import(orm_dir + 'Genders.orm.js');


app.post('/API/Genders/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Genders saved <a href='/'>home</a>');
});

app.get('/API/Genders/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Genders.rawAttributes);

	__.each(Genders.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Genders',to_template); //which loads views/Genders.dust
});

app.get('/API/Genders/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Genders'); //which loads views/Genders.dust
});


//importing Networks from table cred:Networks
var Networks = sequelize.import(orm_dir + 'Networks.orm.js');


app.post('/API/Networks/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Networks saved <a href='/'>home</a>');
});

app.get('/API/Networks/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Networks.rawAttributes);

	__.each(Networks.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Networks',to_template); //which loads views/Networks.dust
});

app.get('/API/Networks/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Networks'); //which loads views/Networks.dust
});


//importing Notes from table cred:Notes
var Notes = sequelize.import(orm_dir + 'Notes.orm.js');
// row_id looks like an association
// User_id looks like an association


app.post('/API/Notes/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Notes saved <a href='/'>home</a>');
});

app.get('/API/Notes/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Notes.rawAttributes);

	__.each(Notes.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Notes',to_template); //which loads views/Notes.dust
});

app.get('/API/Notes/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Notes'); //which loads views/Notes.dust
});


//importing Phones from table cred:Phones
var Phones = sequelize.import(orm_dir + 'Phones.orm.js');


app.post('/API/Phones/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Phones saved <a href='/'>home</a>');
});

app.get('/API/Phones/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Phones.rawAttributes);

	__.each(Phones.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Phones',to_template); //which loads views/Phones.dust
});

app.get('/API/Phones/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Phones'); //which loads views/Phones.dust
});


//importing ProviderCarriers from table cred:ProviderCarriers
var ProviderCarriers = sequelize.import(orm_dir + 'ProviderCarriers.orm.js');
// Provider_id looks like an association
// Carrier_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderCarriers/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderCarriers saved <a href='/'>home</a>');
});

app.get('/API/ProviderCarriers/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderCarriers.rawAttributes);

	__.each(ProviderCarriers.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderCarriers',to_template); //which loads views/ProviderCarriers.dust
});

app.get('/API/ProviderCarriers/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderCarriers'); //which loads views/ProviderCarriers.dust
});


//importing ProviderCoverages from table cred:ProviderCoverages
var ProviderCoverages = sequelize.import(orm_dir + 'ProviderCoverages.orm.js');
// Provider_id looks like an association
// State_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderCoverages/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderCoverages saved <a href='/'>home</a>');
});

app.get('/API/ProviderCoverages/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderCoverages.rawAttributes);

	__.each(ProviderCoverages.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderCoverages',to_template); //which loads views/ProviderCoverages.dust
});

app.get('/API/ProviderCoverages/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderCoverages'); //which loads views/ProviderCoverages.dust
});


//importing ProviderCredentials from table cred:ProviderCredentials
var ProviderCredentials = sequelize.import(orm_dir + 'ProviderCredentials.orm.js');
// Provider_id looks like an association
// CredentialOrganization_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderCredentials/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderCredentials saved <a href='/'>home</a>');
});

app.get('/API/ProviderCredentials/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderCredentials.rawAttributes);

	__.each(ProviderCredentials.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderCredentials',to_template); //which loads views/ProviderCredentials.dust
});

app.get('/API/ProviderCredentials/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderCredentials'); //which loads views/ProviderCredentials.dust
});


//importing ProviderEducations from table cred:ProviderEducations
var ProviderEducations = sequelize.import(orm_dir + 'ProviderEducations.orm.js');
// Provider_id looks like an association
// ProviderSpeciality_id looks like an association
// EducationInstitution_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderEducations/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderEducations saved <a href='/'>home</a>');
});

app.get('/API/ProviderEducations/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderEducations.rawAttributes);

	__.each(ProviderEducations.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderEducations',to_template); //which loads views/ProviderEducations.dust
});

app.get('/API/ProviderEducations/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderEducations'); //which loads views/ProviderEducations.dust
});


//importing ProviderEducationsProviderEducations from table cred:ProviderEducationsProviderEducations
var ProviderEducationsProviderEducations = sequelize.import(orm_dir + 'ProviderEducationsProviderEducations.orm.js');
// ProviderEducation_id looks like an association


app.post('/API/ProviderEducationsProviderEducations/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderEducationsProviderEducations saved <a href='/'>home</a>');
});

app.get('/API/ProviderEducationsProviderEducations/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderEducationsProviderEducations.rawAttributes);

	__.each(ProviderEducationsProviderEducations.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderEducationsProviderEducations',to_template); //which loads views/ProviderEducationsProviderEducations.dust
});

app.get('/API/ProviderEducationsProviderEducations/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderEducationsProviderEducations'); //which loads views/ProviderEducationsProviderEducations.dust
});


//importing ProviderHospitals from table cred:ProviderHospitals
var ProviderHospitals = sequelize.import(orm_dir + 'ProviderHospitals.orm.js');
// Provider_id looks like an association
// State_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderHospitals/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderHospitals saved <a href='/'>home</a>');
});

app.get('/API/ProviderHospitals/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderHospitals.rawAttributes);

	__.each(ProviderHospitals.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderHospitals',to_template); //which loads views/ProviderHospitals.dust
});

app.get('/API/ProviderHospitals/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderHospitals'); //which loads views/ProviderHospitals.dust
});


//importing ProviderLicenses from table cred:ProviderLicenses
var ProviderLicenses = sequelize.import(orm_dir + 'ProviderLicenses.orm.js');
// Provider_id looks like an association
// ProviderSpeciality_id looks like an association
// State_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderLicenses/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderLicenses saved <a href='/'>home</a>');
});

app.get('/API/ProviderLicenses/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderLicenses.rawAttributes);

	__.each(ProviderLicenses.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderLicenses',to_template); //which loads views/ProviderLicenses.dust
});

app.get('/API/ProviderLicenses/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderLicenses'); //which loads views/ProviderLicenses.dust
});


//importing ProviderNetworks from table cred:ProviderNetworks
var ProviderNetworks = sequelize.import(orm_dir + 'ProviderNetworks.orm.js');
// Provider_id looks like an association
// Network_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderNetworks/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderNetworks saved <a href='/'>home</a>');
});

app.get('/API/ProviderNetworks/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderNetworks.rawAttributes);

	__.each(ProviderNetworks.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderNetworks',to_template); //which loads views/ProviderNetworks.dust
});

app.get('/API/ProviderNetworks/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderNetworks'); //which loads views/ProviderNetworks.dust
});


//importing ProviderReferences from table cred:ProviderReferences
var ProviderReferences = sequelize.import(orm_dir + 'ProviderReferences.orm.js');
// Provider_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association


app.post('/API/ProviderReferences/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderReferences saved <a href='/'>home</a>');
});

app.get('/API/ProviderReferences/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderReferences.rawAttributes);

	__.each(ProviderReferences.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderReferences',to_template); //which loads views/ProviderReferences.dust
});

app.get('/API/ProviderReferences/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderReferences'); //which loads views/ProviderReferences.dust
});


//importing ProviderSpecialitys from table cred:ProviderSpecialitys
var ProviderSpecialitys = sequelize.import(orm_dir + 'ProviderSpecialitys.orm.js');
// Provider_id looks like an association
// Speciality_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association
// Board_id looks like an association


app.post('/API/ProviderSpecialitys/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderSpecialitys saved <a href='/'>home</a>');
});

app.get('/API/ProviderSpecialitys/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderSpecialitys.rawAttributes);

	__.each(ProviderSpecialitys.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderSpecialitys',to_template); //which loads views/ProviderSpecialitys.dust
});

app.get('/API/ProviderSpecialitys/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderSpecialitys'); //which loads views/ProviderSpecialitys.dust
});


//importing ProviderStatuss from table cred:ProviderStatuss
var ProviderStatuss = sequelize.import(orm_dir + 'ProviderStatuss.orm.js');


app.post('/API/ProviderStatuss/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProviderStatuss saved <a href='/'>home</a>');
});

app.get('/API/ProviderStatuss/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProviderStatuss.rawAttributes);

	__.each(ProviderStatuss.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProviderStatuss',to_template); //which loads views/ProviderStatuss.dust
});

app.get('/API/ProviderStatuss/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProviderStatuss'); //which loads views/ProviderStatuss.dust
});


//importing Providers from table cred:Providers
var Providers = sequelize.import(orm_dir + 'Providers.orm.js');
// ProviderStatus_id looks like an association
// Birth_Address_id looks like an association
// Gender_id looks like an association
// Home_Phone_id looks like an association
// Home_Address_id looks like an association
// Corr_Phone_id looks like an association
// Corr_Address_id looks like an association
// Corr_Fax_Phone_id looks like an association


app.post('/API/Providers/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Providers saved <a href='/'>home</a>');
});

app.get('/API/Providers/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Providers.rawAttributes);

	__.each(Providers.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Providers',to_template); //which loads views/Providers.dust
});

app.get('/API/Providers/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Providers'); //which loads views/Providers.dust
});


//importing ProvidersProviderSpecialityses from table cred:ProvidersProviderSpecialityses
var ProvidersProviderSpecialityses = sequelize.import(orm_dir + 'ProvidersProviderSpecialityses.orm.js');
// ProviderSpeciality_id looks like an association
// Provider_id looks like an association


app.post('/API/ProvidersProviderSpecialityses/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('ProvidersProviderSpecialityses saved <a href='/'>home</a>');
});

app.get('/API/ProvidersProviderSpecialityses/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(ProvidersProviderSpecialityses.rawAttributes);

	__.each(ProvidersProviderSpecialityses.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('ProvidersProviderSpecialityses',to_template); //which loads views/ProvidersProviderSpecialityses.dust
});

app.get('/API/ProvidersProviderSpecialityses/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('ProvidersProviderSpecialityses'); //which loads views/ProvidersProviderSpecialityses.dust
});


//importing Specialitys from table cred:Specialitys
var Specialitys = sequelize.import(orm_dir + 'Specialitys.orm.js');
// taxonomy_id looks like an association


app.post('/API/Specialitys/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Specialitys saved <a href='/'>home</a>');
});

app.get('/API/Specialitys/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Specialitys.rawAttributes);

	__.each(Specialitys.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Specialitys',to_template); //which loads views/Specialitys.dust
});

app.get('/API/Specialitys/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Specialitys'); //which loads views/Specialitys.dust
});


//importing States from table cred:States
var States = sequelize.import(orm_dir + 'States.orm.js');


app.post('/API/States/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('States saved <a href='/'>home</a>');
});

app.get('/API/States/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(States.rawAttributes);

	__.each(States.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('States',to_template); //which loads views/States.dust
});

app.get('/API/States/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('States'); //which loads views/States.dust
});


//importing TagLinks from table cred:TagLinks
var TagLinks = sequelize.import(orm_dir + 'TagLinks.orm.js');
// row_id looks like an association
// Tag_id looks like an association
// User_id looks like an association


app.post('/API/TagLinks/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('TagLinks saved <a href='/'>home</a>');
});

app.get('/API/TagLinks/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(TagLinks.rawAttributes);

	__.each(TagLinks.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('TagLinks',to_template); //which loads views/TagLinks.dust
});

app.get('/API/TagLinks/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('TagLinks'); //which loads views/TagLinks.dust
});


//importing Tags from table cred:Tags
var Tags = sequelize.import(orm_dir + 'Tags.orm.js');


app.post('/API/Tags/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Tags saved <a href='/'>home</a>');
});

app.get('/API/Tags/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Tags.rawAttributes);

	__.each(Tags.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Tags',to_template); //which loads views/Tags.dust
});

app.get('/API/Tags/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Tags'); //which loads views/Tags.dust
});


//importing Tests from table cred:Tests
var Tests = sequelize.import(orm_dir + 'Tests.orm.js');
//I did not understand what to do with confusingdate
//I did not understand what to do with confusingenum


app.post('/API/Tests/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Tests saved <a href='/'>home</a>');
});

app.get('/API/Tests/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Tests.rawAttributes);

	__.each(Tests.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Tests',to_template); //which loads views/Tests.dust
});

app.get('/API/Tests/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Tests'); //which loads views/Tests.dust
});


//importing Users from table cred:Users
var Users = sequelize.import(orm_dir + 'Users.orm.js');


app.post('/API/Users/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('Users saved <a href='/'>home</a>');
});

app.get('/API/Users/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(Users.rawAttributes);

	__.each(Users.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('Users',to_template); //which loads views/Users.dust
});

app.get('/API/Users/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('Users'); //which loads views/Users.dust
});


//importing rows from table cred:rows
var rows = sequelize.import(orm_dir + 'rows.orm.js');


app.post('/API/rows/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('rows saved <a href='/'>home</a>');
});

app.get('/API/rows/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(rows.rawAttributes);

	__.each(rows.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('rows',to_template); //which loads views/rows.dust
});

app.get('/API/rows/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('rows'); //which loads views/rows.dust
});


//importing taxonomys from table cred:taxonomys
var taxonomys = sequelize.import(orm_dir + 'taxonomys.orm.js');


app.post('/API/taxonomys/', ensureAuthenticated, function(req, res){
	//Save the object after getting the post from the form...
	res.send('taxonomys saved <a href='/'>home</a>');
});

app.get('/API/taxonomys/', ensureAuthenticated, function(req, res){
	//Create a new object here...

	var to_template = {};

	console.log(taxonomys.rawAttributes);

	__.each(taxonomys.rawAttributes,function(this_value,this_key){
		if( typeof ModelCacheGLOBAL[this_key] != 'undefined'){
			//then this is a select box
			//or something...
			this_contents = ModelCacheGLOBAL[this_key];
			to_template[this_key] = {			
				is_array: true,
				contents: this_contents
			};
		}else{
			//nothing here... wait for any actual values...
		}
	});

	console.log('Just made this bad boy');
	prettyJSON(to_template);


  	res.render('taxonomys',to_template); //which loads views/taxonomys.dust
});

app.get('/API/taxonomys/:id/', ensureAuthenticated, function(req, res){
	//LOAD SEQUELIZE HERE using id!!
  	res.render('taxonomys'); //which loads views/taxonomys.dust
});




//This what makes express into our webserver....
http.createServer(app).listen(app.get('port'), function(){
  console.log('Express server listening on port ' + app.get('port'));
});


//States.hasOne(
States.hasMany(
		Addresss,
		{
//			as: 		'State_id', 
			foreignKey: 	'State_id'
		}
		);

buildCache(States,'State_id');


//Countys.hasOne(
Countys.hasMany(
		Addresss,
		{
//			as: 		'County_id', 
			foreignKey: 	'County_id'
		}
		);

buildCache(Countys,'County_id');


//Addresss.hasOne(
Addresss.hasMany(
		Boards,
		{
//			as: 		'Address_id', 
			foreignKey: 	'Address_id'
		}
		);

buildCache(Addresss,'Address_id');


//Phones.hasOne(
Phones.hasMany(
		Boards,
		{
//			as: 		'Phone_id', 
			foreignKey: 	'Phone_id'
		}
		);

buildCache(Phones,'Phone_id');


//Phones.hasOne(
Phones.hasMany(
		Boards,
		{
//			as: 		'Fax_Phone_id', 
			foreignKey: 	'Fax_Phone_id'
		}
		);

buildCache(Phones,'Fax_Phone_id');


//Addresss.hasOne(
Addresss.hasMany(
		EducationInstitutions,
		{
//			as: 		'Address_id', 
			foreignKey: 	'Address_id'
		}
		);

buildCache(Addresss,'Address_id');


//Phones.hasOne(
Phones.hasMany(
		EducationInstitutions,
		{
//			as: 		'Phone_id', 
			foreignKey: 	'Phone_id'
		}
		);

buildCache(Phones,'Phone_id');


//rows.hasOne(
rows.hasMany(
		Notes,
		{
//			as: 		'row_id', 
			foreignKey: 	'row_id'
		}
		);

buildCache(rows,'row_id');


//Users.hasOne(
Users.hasMany(
		Notes,
		{
//			as: 		'User_id', 
			foreignKey: 	'User_id'
		}
		);

buildCache(Users,'User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderCarriers,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//Carriers.hasOne(
Carriers.hasMany(
		ProviderCarriers,
		{
//			as: 		'Carrier_id', 
			foreignKey: 	'Carrier_id'
		}
		);

buildCache(Carriers,'Carrier_id');


//Users.hasOne(
Users.hasMany(
		ProviderCarriers,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderCarriers,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderCoverages,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//States.hasOne(
States.hasMany(
		ProviderCoverages,
		{
//			as: 		'State_id', 
			foreignKey: 	'State_id'
		}
		);

buildCache(States,'State_id');


//Users.hasOne(
Users.hasMany(
		ProviderCoverages,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderCoverages,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderCredentials,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//CredentialOrganizations.hasOne(
CredentialOrganizations.hasMany(
		ProviderCredentials,
		{
//			as: 		'CredentialOrganization_id', 
			foreignKey: 	'CredentialOrganization_id'
		}
		);

buildCache(CredentialOrganizations,'CredentialOrganization_id');


//Users.hasOne(
Users.hasMany(
		ProviderCredentials,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderCredentials,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderEducations,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//ProviderSpecialitys.hasOne(
ProviderSpecialitys.hasMany(
		ProviderEducations,
		{
//			as: 		'ProviderSpeciality_id', 
			foreignKey: 	'ProviderSpeciality_id'
		}
		);

buildCache(ProviderSpecialitys,'ProviderSpeciality_id');


//EducationInstitutions.hasOne(
EducationInstitutions.hasMany(
		ProviderEducations,
		{
//			as: 		'EducationInstitution_id', 
			foreignKey: 	'EducationInstitution_id'
		}
		);

buildCache(EducationInstitutions,'EducationInstitution_id');


//Users.hasOne(
Users.hasMany(
		ProviderEducations,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderEducations,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//ProviderEducations.hasOne(
ProviderEducations.hasMany(
		ProviderEducationsProviderEducations,
		{
//			as: 		'ProviderEducation_id', 
			foreignKey: 	'ProviderEducation_id'
		}
		);

buildCache(ProviderEducations,'ProviderEducation_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderHospitals,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//States.hasOne(
States.hasMany(
		ProviderHospitals,
		{
//			as: 		'State_id', 
			foreignKey: 	'State_id'
		}
		);

buildCache(States,'State_id');


//Users.hasOne(
Users.hasMany(
		ProviderHospitals,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderHospitals,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderLicenses,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//ProviderSpecialitys.hasOne(
ProviderSpecialitys.hasMany(
		ProviderLicenses,
		{
//			as: 		'ProviderSpeciality_id', 
			foreignKey: 	'ProviderSpeciality_id'
		}
		);

buildCache(ProviderSpecialitys,'ProviderSpeciality_id');


//States.hasOne(
States.hasMany(
		ProviderLicenses,
		{
//			as: 		'State_id', 
			foreignKey: 	'State_id'
		}
		);

buildCache(States,'State_id');


//Users.hasOne(
Users.hasMany(
		ProviderLicenses,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderLicenses,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderNetworks,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//Networks.hasOne(
Networks.hasMany(
		ProviderNetworks,
		{
//			as: 		'Network_id', 
			foreignKey: 	'Network_id'
		}
		);

buildCache(Networks,'Network_id');


//Users.hasOne(
Users.hasMany(
		ProviderNetworks,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderNetworks,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderReferences,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//Users.hasOne(
Users.hasMany(
		ProviderReferences,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderReferences,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Providers.hasOne(
Providers.hasMany(
		ProviderSpecialitys,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//Specialitys.hasOne(
Specialitys.hasMany(
		ProviderSpecialitys,
		{
//			as: 		'Speciality_id', 
			foreignKey: 	'Speciality_id'
		}
		);

buildCache(Specialitys,'Speciality_id');


//Users.hasOne(
Users.hasMany(
		ProviderSpecialitys,
		{
//			as: 		'created_by_User_id', 
			foreignKey: 	'created_by_User_id'
		}
		);

buildCache(Users,'created_by_User_id');


//Users.hasOne(
Users.hasMany(
		ProviderSpecialitys,
		{
//			as: 		'modified_by_User_id', 
			foreignKey: 	'modified_by_User_id'
		}
		);

buildCache(Users,'modified_by_User_id');


//Boards.hasOne(
Boards.hasMany(
		ProviderSpecialitys,
		{
//			as: 		'Board_id', 
			foreignKey: 	'Board_id'
		}
		);

buildCache(Boards,'Board_id');


//ProviderStatuss.hasOne(
ProviderStatuss.hasMany(
		Providers,
		{
//			as: 		'ProviderStatus_id', 
			foreignKey: 	'ProviderStatus_id'
		}
		);

buildCache(ProviderStatuss,'ProviderStatus_id');


//Addresss.hasOne(
Addresss.hasMany(
		Providers,
		{
//			as: 		'Birth_Address_id', 
			foreignKey: 	'Birth_Address_id'
		}
		);

buildCache(Addresss,'Birth_Address_id');


//Genders.hasOne(
Genders.hasMany(
		Providers,
		{
//			as: 		'Gender_id', 
			foreignKey: 	'Gender_id'
		}
		);

buildCache(Genders,'Gender_id');


//Phones.hasOne(
Phones.hasMany(
		Providers,
		{
//			as: 		'Home_Phone_id', 
			foreignKey: 	'Home_Phone_id'
		}
		);

buildCache(Phones,'Home_Phone_id');


//Addresss.hasOne(
Addresss.hasMany(
		Providers,
		{
//			as: 		'Home_Address_id', 
			foreignKey: 	'Home_Address_id'
		}
		);

buildCache(Addresss,'Home_Address_id');


//Phones.hasOne(
Phones.hasMany(
		Providers,
		{
//			as: 		'Corr_Phone_id', 
			foreignKey: 	'Corr_Phone_id'
		}
		);

buildCache(Phones,'Corr_Phone_id');


//Addresss.hasOne(
Addresss.hasMany(
		Providers,
		{
//			as: 		'Corr_Address_id', 
			foreignKey: 	'Corr_Address_id'
		}
		);

buildCache(Addresss,'Corr_Address_id');


//Phones.hasOne(
Phones.hasMany(
		Providers,
		{
//			as: 		'Corr_Fax_Phone_id', 
			foreignKey: 	'Corr_Fax_Phone_id'
		}
		);

buildCache(Phones,'Corr_Fax_Phone_id');


//ProviderSpecialitys.hasOne(
ProviderSpecialitys.hasMany(
		ProvidersProviderSpecialityses,
		{
//			as: 		'ProviderSpeciality_id', 
			foreignKey: 	'ProviderSpeciality_id'
		}
		);

buildCache(ProviderSpecialitys,'ProviderSpeciality_id');


//Providers.hasOne(
Providers.hasMany(
		ProvidersProviderSpecialityses,
		{
//			as: 		'Provider_id', 
			foreignKey: 	'Provider_id'
		}
		);

buildCache(Providers,'Provider_id');


//taxonomys.hasOne(
taxonomys.hasMany(
		Specialitys,
		{
//			as: 		'taxonomy_id', 
			foreignKey: 	'taxonomy_id'
		}
		);

buildCache(taxonomys,'taxonomy_id');


//rows.hasOne(
rows.hasMany(
		TagLinks,
		{
//			as: 		'row_id', 
			foreignKey: 	'row_id'
		}
		);

buildCache(rows,'row_id');


//Tags.hasOne(
Tags.hasMany(
		TagLinks,
		{
//			as: 		'Tag_id', 
			foreignKey: 	'Tag_id'
		}
		);

buildCache(Tags,'Tag_id');


//Users.hasOne(
Users.hasMany(
		TagLinks,
		{
//			as: 		'User_id', 
			foreignKey: 	'User_id'
		}
		);

buildCache(Users,'User_id');

