//Generated by buildORM from the cred:Boards
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Boards', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    name: { type: Sequelize.STRING },
    Address_id: { type: Sequelize.INTEGER },
    Phone_id: { type: Sequelize.INTEGER },
    Fax_Phone_id: { type: Sequelize.INTEGER },
    website: { type: Sequelize.STRING },
    email: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
