//Generated by buildORM from the cred:CredentialOrganizations
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('CredentialOrganizations', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    name: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
