//Generated by buildORM from the cred:Documents
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Documents', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    Provider_id: { type: Sequelize.INTEGER },
    DocumentType_id: { type: Sequelize.INTEGER },
    documentURL: { type: Sequelize.STRING },
    imageURL: { type: Sequelize.STRING },
    container: { type: Sequelize.STRING },
    filename: { type: Sequelize.STRING },
    select_name: { type: Sequelize.STRING },
    token: { type: Sequelize.STRING },
    expiration_date: { type: Sequelize.DATE },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
