//Generated by buildORM from the cred:EducationLevels
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('EducationLevels', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    level_name: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
