//Generated by buildORM from the cred:EducationLevels
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('EducationLevels', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    name: { type: Sequelize.STRING },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
