//Generated by buildORM from the cred:Genders
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Genders', {
    id: { type: Sequelize.INTEGER },
    gender_name: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
