

var HTMLCache = {};
var ModelCache = {};

exports.HTMLCache = HTMLCache;
exports.ModelCache = ModelCache;

//Javascript does not allow for default arguments into functions
//this handles the problem for functions
//with unpredicatable arguments
function has_default(arg, def) {
   return (typeof arg == 'undefined' ? def : arg);
}



function buildCache(ORM,select_name){

        var object_type;
        var select_html;
        var selected_col;
        var data_cache = [];
//add code for auto-complete detection engine...

        object_type = ORM.name;
        //if we passed in a select_name, use it, otherwise use the default
        select_name = has_default(select_name, object_type + "_id");
        select_html = "<select name='" + select_name + "'>\n";

        console.log("object_type: " + object_type + "\n");
        console.log("select_name: " + select_name + "\n");

        ORM.findAll().success(function(things) {

                __.each(things,function(a_thing){
                        //lets determine what the variable
                        //from the table should be the label for the
                        //select box...
                        if(selected_col === undefined){
                                selected = a_thing.attributes;
                                __.each(selected,function(key,value){
                                if(key.indexOf("name") !== -1){
                                        //then this is my select variable..
                                                selected_col = key;
                //                              console.log("inside key" + key);
                                        }
                                });
                        }

                        select_html = select_html               +
                                        "<option value='"       +
                                        a_thing.id              +
                                        "'>"                    +
                                a_thing[selected_col] + "</option>\n";
                        my_value = a_thing[selected_col];

                        data_cache.push({
                                                id: a_thing.id,
                                                value: my_value
                                        });

                });
                select_html = select_html + "</select>\n";
                HTMLCache[select_name] = select_html;
                ModelCache[select_name] = data_cache;
        });
}

exports.buildCache = buildCache;


//Begin autogenerated Objects...

//importing Addresss from table cred:Addresss
var Addresss = sequelize.import(__dirname + '/Addresss.orm.js');
exports.Addresss = Addresss;
// State_id looks like an association
// County_id looks like an association

//importing Boards from table cred:Boards
var Boards = sequelize.import(__dirname + '/Boards.orm.js');
exports.Boards = Boards;
// Address_id looks like an association
// Phone_id looks like an association
// Fax_Phone_id looks like an association

//importing Carriers from table cred:Carriers
var Carriers = sequelize.import(__dirname + '/Carriers.orm.js');
exports.Carriers = Carriers;

//importing Countys from table cred:Countys
var Countys = sequelize.import(__dirname + '/Countys.orm.js');
exports.Countys = Countys;

//importing CredentialOrganizations from table cred:CredentialOrganizations
var CredentialOrganizations = sequelize.import(__dirname + '/CredentialOrganizations.orm.js');
exports.CredentialOrganizations = CredentialOrganizations;

//importing EducationInstitutions from table cred:EducationInstitutions
var EducationInstitutions = sequelize.import(__dirname + '/EducationInstitutions.orm.js');
exports.EducationInstitutions = EducationInstitutions;
// Address_id looks like an association
// Phone_id looks like an association

//importing EducationLevels from table cred:EducationLevels
var EducationLevels = sequelize.import(__dirname + '/EducationLevels.orm.js');
exports.EducationLevels = EducationLevels;

//importing Genders from table cred:Genders
var Genders = sequelize.import(__dirname + '/Genders.orm.js');
exports.Genders = Genders;

//importing Networks from table cred:Networks
var Networks = sequelize.import(__dirname + '/Networks.orm.js');
exports.Networks = Networks;

//importing Notes from table cred:Notes
var Notes = sequelize.import(__dirname + '/Notes.orm.js');
exports.Notes = Notes;
// row_id looks like an association
// User_id looks like an association

//importing Phones from table cred:Phones
var Phones = sequelize.import(__dirname + '/Phones.orm.js');
exports.Phones = Phones;

//importing ProviderCarriers from table cred:ProviderCarriers
var ProviderCarriers = sequelize.import(__dirname + '/ProviderCarriers.orm.js');
exports.ProviderCarriers = ProviderCarriers;
// Provider_id looks like an association
// Carrier_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderCoverages from table cred:ProviderCoverages
var ProviderCoverages = sequelize.import(__dirname + '/ProviderCoverages.orm.js');
exports.ProviderCoverages = ProviderCoverages;
// Provider_id looks like an association
// State_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderCredentials from table cred:ProviderCredentials
var ProviderCredentials = sequelize.import(__dirname + '/ProviderCredentials.orm.js');
exports.ProviderCredentials = ProviderCredentials;
// Provider_id looks like an association
// CredentialOrganization_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderEducations from table cred:ProviderEducations
var ProviderEducations = sequelize.import(__dirname + '/ProviderEducations.orm.js');
exports.ProviderEducations = ProviderEducations;
// Provider_id looks like an association
// ProviderSpeciality_id looks like an association
// EducationInstitution_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderEducationsProviderEducations from table cred:ProviderEducationsProviderEducations
var ProviderEducationsProviderEducations = sequelize.import(__dirname + '/ProviderEducationsProviderEducations.orm.js');
exports.ProviderEducationsProviderEducations = ProviderEducationsProviderEducations;
// ProviderEducation_id looks like an association

//importing ProviderHospitals from table cred:ProviderHospitals
var ProviderHospitals = sequelize.import(__dirname + '/ProviderHospitals.orm.js');
exports.ProviderHospitals = ProviderHospitals;
// Provider_id looks like an association
// State_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderLicenses from table cred:ProviderLicenses
var ProviderLicenses = sequelize.import(__dirname + '/ProviderLicenses.orm.js');
exports.ProviderLicenses = ProviderLicenses;
// Provider_id looks like an association
// ProviderSpeciality_id looks like an association
// State_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderNetworks from table cred:ProviderNetworks
var ProviderNetworks = sequelize.import(__dirname + '/ProviderNetworks.orm.js');
exports.ProviderNetworks = ProviderNetworks;
// Provider_id looks like an association
// Network_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderReferences from table cred:ProviderReferences
var ProviderReferences = sequelize.import(__dirname + '/ProviderReferences.orm.js');
exports.ProviderReferences = ProviderReferences;
// Provider_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association

//importing ProviderSpecialitys from table cred:ProviderSpecialitys
var ProviderSpecialitys = sequelize.import(__dirname + '/ProviderSpecialitys.orm.js');
exports.ProviderSpecialitys = ProviderSpecialitys;
// Provider_id looks like an association
// Speciality_id looks like an association
// created_by_User_id looks like an association
// modified_by_User_id looks like an association
// Board_id looks like an association

//importing ProviderStatuss from table cred:ProviderStatuss
var ProviderStatuss = sequelize.import(__dirname + '/ProviderStatuss.orm.js');
exports.ProviderStatuss = ProviderStatuss;

//importing Providers from table cred:Providers
var Providers = sequelize.import(__dirname + '/Providers.orm.js');
exports.Providers = Providers;
// ProviderStatus_id looks like an association
// Birth_Address_id looks like an association
// Gender_id looks like an association
// Home_Phone_id looks like an association
// Home_Address_id looks like an association
// Corr_Phone_id looks like an association
// Corr_Address_id looks like an association
// Corr_Fax_Phone_id looks like an association

//importing ProvidersProviderSpecialityses from table cred:ProvidersProviderSpecialityses
var ProvidersProviderSpecialityses = sequelize.import(__dirname + '/ProvidersProviderSpecialityses.orm.js');
exports.ProvidersProviderSpecialityses = ProvidersProviderSpecialityses;
// ProviderSpeciality_id looks like an association
// Provider_id looks like an association

//importing Specialitys from table cred:Specialitys
var Specialitys = sequelize.import(__dirname + '/Specialitys.orm.js');
exports.Specialitys = Specialitys;
// taxonomy_id looks like an association

//importing States from table cred:States
var States = sequelize.import(__dirname + '/States.orm.js');
exports.States = States;

//importing TagLinks from table cred:TagLinks
var TagLinks = sequelize.import(__dirname + '/TagLinks.orm.js');
exports.TagLinks = TagLinks;
// row_id looks like an association
// Tag_id looks like an association
// User_id looks like an association

//importing Tags from table cred:Tags
var Tags = sequelize.import(__dirname + '/Tags.orm.js');
exports.Tags = Tags;

//importing Tests from table cred:Tests
var Tests = sequelize.import(__dirname + '/Tests.orm.js');
exports.Tests = Tests;
//I did not understand what to do with confusingdate
//I did not understand what to do with confusingenum

//importing Users from table cred:Users
var Users = sequelize.import(__dirname + '/Users.orm.js');
exports.Users = Users;

//importing rows from table cred:rows
var rows = sequelize.import(__dirname + '/rows.orm.js');
exports.rows = rows;

//importing taxonomys from table cred:taxonomys
var taxonomys = sequelize.import(__dirname + '/taxonomys.orm.js');
exports.taxonomys = taxonomys;


 //OK we have the objects.. Lets do the associations now.... 