//Generated by buildORM from the cred:Notes
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Notes', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    table: { type: Sequelize.STRING },
    row_id: { type: Sequelize.INTEGER },
    note: { type: Sequelize.STRING },
    User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
