//Generated by buildORM from the cred:ProviderStatuss
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('ProviderStatuss', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    name: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
