//Generated by buildORM from the cred:ProviderCoverages
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('ProviderCoverages', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    Provider_id: { type: Sequelize.INTEGER },
    is_self_insured: { type: Sequelize.BOOLEAN },
    name: { type: Sequelize.STRING },
    street: { type: Sequelize.STRING },
    ste_apt_etc: { type: Sequelize.STRING },
    city: { type: Sequelize.STRING },
    State_id: { type: Sequelize.INTEGER },
    zip_code: { type: Sequelize.INTEGER },
    phone: { type: Sequelize.INTEGER },
    policy_number: { type: Sequelize.INTEGER },
    effective_date: { type: Sequelize.DATE },
    expiration_date: { type: Sequelize.DATE },
    occurrence_limit: { type: Sequelize.INTEGER },
    aggregate_limit: { type: Sequelize.INTEGER },
    coverage: { type: Sequelize.STRING },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
