//Generated by buildORM from the cred:ProviderEducations
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('ProviderEducations', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    Provider_id: { type: Sequelize.INTEGER },
    ProviderSpeciality_id: { type: Sequelize.INTEGER },
    attendance_period_start: { type: Sequelize.DATE },
    attendance_period_end: { type: Sequelize.DATE },
    EducationInstitution_id: { type: Sequelize.INTEGER },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
