//Generated by buildORM from the cred:ProviderCredentials
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('ProviderCredentials', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    Provider_id: { type: Sequelize.INTEGER },
    CredentialOrganization_id: { type: Sequelize.INTEGER },
    credential_date: { type: Sequelize.DATE },
    recredential_date: { type: Sequelize.DATE },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
