//Generated by buildORM from the cred:ProviderLicenses
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('ProviderLicenses', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    Provider_id: { type: Sequelize.INTEGER },
    ProviderSpeciality_id: { type: Sequelize.INTEGER },
    license_number: { type: Sequelize.STRING },
    State_id: { type: Sequelize.INTEGER },
    issue_date: { type: Sequelize.DATE },
    expiration_date: { type: Sequelize.DATE },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
