//Generated by buildORM from the cred:ProviderHospitals
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('ProviderHospitals', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    Provider_id: { type: Sequelize.INTEGER },
    is_primary: { type: Sequelize.BOOLEAN },
    has_hospital_privaleges: { type: Sequelize.BOOLEAN },
    Hospital_npi: { type: Sequelize.INTEGER },
    name: { type: Sequelize.STRING },
    start_date: { type: Sequelize.DATE },
    street: { type: Sequelize.STRING },
    ste_apt_etc: { type: Sequelize.STRING },
    city: { type: Sequelize.STRING },
    State_id: { type: Sequelize.INTEGER },
    zip_code: { type: Sequelize.INTEGER },
    phone: { type: Sequelize.INTEGER },
    fax: { type: Sequelize.INTEGER },
    email_address: { type: Sequelize.STRING },
    is_unrestricted_privileges: { type: Sequelize.BOOLEAN },
    privileges_type: { type: Sequelize.STRING },
    is_privileges_temp: { type: Sequelize.BOOLEAN },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
