//Generated by buildORM from the cred:ProviderCarriers
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('ProviderCarriers', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    Provider_id: { type: Sequelize.INTEGER },
    Carrier_id: { type: Sequelize.INTEGER },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
