//Generated by buildORM from the cred:Specialitys
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Specialitys', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    specialty_abbreviation: { type: Sequelize.STRING },
    specialty_name: { type: Sequelize.STRING },
    created_by_User_id: { type: Sequelize.INTEGER },
    modified_by_User_id: { type: Sequelize.INTEGER },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
