//Generated by buildORM from the cred:Specialitys
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Specialitys', {
    SpecialtyID: { type: Sequelize.INTEGER  ,primaryKey: true },
    SpecialtyAbbreviation: { type: Sequelize.STRING },
    SpecialtyName: { type: Sequelize.STRING },
    DateCreated: { type: Sequelize.DATE },
    CreatedBy: { type: Sequelize.STRING },
    DateModified: { type: Sequelize.DATE },
    ModifiedBy: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
