//Generated by buildORM from the cred:States
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('States', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    state_name: { type: Sequelize.STRING },
    state_abbr: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
