//Generated by buildORM from the cred:Tags
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Tags', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    tag: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
