//Generated by buildORM from the cred:Tags
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Tags', {
    id: { type: Sequelize.INTEGER  ,primaryKey: true },
    name: { type: Sequelize.STRING },
    createdAt: { type: Sequelize.DATE },
    updatedAt: { type: Sequelize.DATE }
  },
	{freezeTableName: true}
)
}
