//Generated by buildORM from the cred:Users
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Users', {
    id: { type: Sequelize.INTEGER },
    email: { type: Sequelize.STRING },
    first_name: { type: Sequelize.STRING },
    last_name: { type: Sequelize.STRING }
  },
	{freezeTableName: true}
)
}
